### ISSUE TITLE
[Enhancement] Picking blocks 

### ISSUE THREAD

**Issue by NonStop4top** [LoneDev6/Issues-ItemsAdder#211]
I saw someone posted almost the same bug but i found something quite different and maybe it's not a big deal for players and for you but i wanted you to know this glitch or bug, idk how to call it
In the video you can watch it

When you pick blocks with Middle Button of your mouse but you put blocks that are not full solid or full Squared like flowers, lamps, snow, iron fences, well you will understand... Custom blocks transforms into mushroom blocks in your hand

**Expected behavior**

VIDEO
=================================
https://www.youtube.com/watch?v=KVeRydeic7Q
=================================

**Info (please complete the following information):**
 - Server version: 1.15.2
 - Client version: 1.15.2
 - Plugin version: v2.0.17

**Additional context**

**Comment by LoneDev6** [comment]
Thanks I understand the problem, sadly for now I have no solution, I leave this report open but I don't know if I'll be able to fix it

**Comment by LoneDev6** [comment]
Should be fixed in next update 2.0.31
