### ISSUE TITLE
[BUG] When disabling an item from generating, this item still spawns.

### ISSUE THREAD

**Issue by randomdray** [LoneDev6/Issues-ItemsAdder#230]
**Describe the bug**
When disabling an item from generating, this item still spawns.

**To Reproduce**
Disabled an item through the configuration.

**Expected behavior**
This item should now be disabled.

**Screenshots**
/

**Info (please complete the following information):**
 - Server version: 1.15.2
 - Client version: 1.15.2
 - Plugin version: Latest on the 13th May.

**Comment by LoneDev6** [comment]
I don't understand your issue, please give more details, .yml files examples and screenshots, thanks
