### ISSUE TITLE
[BUG] Resourcepack error message

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/Issues-ItemsAdder#232]
[ItemsAdder] An error occurred when enabling the resourcepack. Please contact admins or disable resourcepacks.

Can you help me? :(

**Comment by LoneDev6** [comment]
Please be sure you followed this tutorial correctly: https://itemsadder.plugin.ga/plugin-usage/resourcepack-hosting

![immagine](https://user-images.githubusercontent.com/27242001/82198761-1124e580-98fd-11ea-9f86-55fe1c4d7fe9.png)

if you're using self-host be sure the port is correctly opened

**Comment by LoneDev6** [comment]
Let me know if it's solved @Deathroner
