### ISSUE TITLE
[Suggestion] More Action on CustomInteractEvent

### ISSUE THREAD

**Issue by brettsaunders21** [LoneDev6/Issues-ItemsAdder#286]
**Is your feature request related to a problem? Please describe.**
The default Minecraft interact event does both right and left click on blocks, I have noticed that the custom one only does right-click.

**Describe the solution you'd like**
Add left click and use event.getAction == Action.LEFT_CLICK_BLOCK to determine if right or left click

**Describe alternatives you've considered**
A separate event is another solution

**Comment by LoneDev6** [comment]
Added in next update :D
