### ISSUE TITLE
A placeholder for the display name of items 

### ISSUE THREAD

**Issue by Jamm95** [LoneDev6/Issues-ItemsAdder#301]
**Is your feature request related to a problem? Please describe.**
When giving players an item with console, they are forced to see the name of the item in the config, with the underscore and all. It's not a huge deal, but it would be nice if there was a way to display the actual name of the item like they see it on the item, even with color. This way, when giving players a "ruby_pickaxe" for example, it will display as "Ruby Pickaxe" with the color the item is displayed as on the item (or whatever you have it named).

**Describe the solution you'd like**
Add a {displayname} placeholder in the locale file.

**Comment by LoneDev6** [comment]
in next update /iagive displays the item name not namespaced id to the player you're giving item to
;)
I will post it today
