### ISSUE TITLE
Dupe Glitch (towny) [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [LoneDev6/Issues-ItemsAdder#308]
**Describe the bug**
Basically, a player isn't in the town of the one that placed the custom blocks and they can break the blocks (it will regenerate then give a copy of the block to the guy), this works with every custom blocks/ores.

**To Reproduce**
1. Go to someone's town (that you're not in).
2. Break the custom blocks in his town.
3. Copies of the block should drop on the floor.

**Expected behavior**
The blocks will dupe itself and generate a copy of themselves.

**Screenshots**
https://www.youtube.com/watch?v=i_WcGCpz0as

**Info (please complete the following information):**
 - Server version: paper 1.15.2 build 370
 - Client version: Minecraft 1.14.4 (vanilla, no custom launcher)
 - Plugin version: 2.0.27

**Additional context**
I have worldguard for spawns, but players uses towny to create their town and protect their buildings as seen in the video above.

**Comment by PhanaticD** [comment]
I am having this issue with worldguard region protections, here is the players description who reported it to me: https://gyazo.com/fcb65ba57167189b0827ee4606e40a72

**Comment by LoneDev6** [comment]
I will pulish an update today, please let me know if now it's okay. Will be 2.0.29
Sadly I triggered this problem after fixing this: https://github.com/LoneDev6/Issues-ItemsAdder/issues/300

**Comment by LoneDev6** [comment]
Reply here if the issue is not fixed, thanks all
