### ISSUE TITLE
[BUG] Big bug / error when breaking ItemsAdder blocks

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/Issues-ItemsAdder#312]
I just updated to version 1.16.1.

I ran into a very annoying bug, I made the recording for you to see. I think it only happens with package items that are added; it gives a message when breaking a block of the ItemsAdder, it happens to all my users. At least from what I tried lightly, it only happens with the new packages added.

And also an error in the console, I'll leave it for you to see, along with the video :( I hope it can be solved, I hope it wasn't an error to switch to this version -.-

**Error:** https://pastebin.com/jcpNSGmX
**Vídeo:**  https://youtu.be/PWbrou6Aqck

**Info (please complete the following information):**
 - Server version: PaperMC 1.16.1
 - Client version: Minecraft 1.16.1
 - Plugin version: ItemsAdder 2.0.31

**Comment by Deathroner** [comment]
- Go with your "Builder Basics" package too

**Comment by Deathroner** [comment]
- Confirmed, only gives problem with external block packages that you add to ItemsAdder

**Comment by Deathroner** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/issues/1257

**Comment by LoneDev6** [comment]
try on a clean server with only itemsadder + protocollib + iaedit.
Anyway I'm 100% sure this is not an issue related to itemsadder itself but a 1.16.1 bug / protocollib bug

**Comment by Deathroner** [comment]
I did the test without ProtocolSupport, and it worked flawlessly, so I guess it's not ItemsAdder that fails, I link it anyway in case you need to know.

**Comment by LoneDev6** [comment]
Thanks, I think it's another plugin interfering or doing some black magic on packets level
You should enable whitelist and try to disable one plugin at a time to see which one is the bad one.
Use plugman to disable plugins while server is on https://dev.bukkit.org/projects/plugman
